p8105\_hw2\_bg2715
================

## Problem 1

Loading data.

``` r
data("instacart")
instacart %>%
  head(3)
```

    ## # A tibble: 3 x 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1        1      49302                 1         1  112108 train               4
    ## 2        1      11109                 2         1  112108 train               4
    ## 3        1      10246                 3         0  112108 train               4
    ## # ... with 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

Short description: This dataset has 1384617 rows and 15 columns. Each
row represent a single item ordered and each column represent a
feature/information of that order. Key variables are “aisle”,
“product\_name”, “order\_dow”, “order\_hour\_of\_day” and so on. For
example, the first line means user 112108 ordered bulgarian yogurt from
aisle yogurt in department dairy eggs at ten o’clock on Thursday.

``` r
ai_df = instacart %>%
  count(aisle) %>%
  arrange(-n)
  knitr::kable(head(ai_df[1:4, ]))
```

| aisle                      |      n |
|:---------------------------|-------:|
| fresh vegetables           | 150609 |
| fresh fruits               | 150473 |
| packaged vegetables fruits |  78493 |
| yogurt                     |  55240 |

There are 134 aisles and the most items ordered from “fresh vegetables”
and “fresh fruits” aisles.

``` r
ai_plot = instacart %>%
  count(aisle) %>%
  filter(n > 10000) %>%
  mutate(aisle = factor(aisle),
         aisle = fct_reorder(aisle, n)) %>% 
  ggplot(aes(x = aisle, y = n)) + geom_point(colour = "#FF0000FF") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5))

ggsave("ai_plot.png")
```

    ## Saving 6 x 3.59 in image

``` r
knitr::include_graphics("ai_plot.png")  
```

<img src="ai_plot.png" width="90%" />

Most of them are less than 40000.

``` r
bdp_df = instacart %>%
  filter(aisle %in% c("baking ingredients", 
                      "dog food care", 
                      "packaged vegetables fruits")) %>%  
  group_by(aisle, product_name) %>%
  summarise(n_times = n()) %>%
  top_n(n = 3)
```

    ## `summarise()` has grouped output by 'aisle'. You can override using the `.groups` argument.

    ## Selecting by n_times

``` r
  knitr::kable(bdp_df)
```

| aisle                      | product\_name                                 | n\_times |
|:---------------------------|:----------------------------------------------|---------:|
| baking ingredients         | Cane Sugar                                    |      336 |
| baking ingredients         | Light Brown Sugar                             |      499 |
| baking ingredients         | Pure Baking Soda                              |      387 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |       28 |
| dog food care              | Small Dog Biscuits                            |       26 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |       30 |
| packaged vegetables fruits | Organic Baby Spinach                          |     9784 |
| packaged vegetables fruits | Organic Blueberries                           |     4966 |
| packaged vegetables fruits | Organic Raspberries                           |     5546 |

The most popular item in “baking ingredients”, “dog food care”, and
“packaged vegetables fruits” is “Light Brown Sugar” (499), “Snack Sticks
Chicken & Rice Recipe Dog Treats” (30) and “Organic Baby Spinach” (9784)
respectively.

``` r
pc_df = instacart %>%
  filter(product_name %in% c("Pink Lady Apples",
                             "Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>%
  summarise(mean_hour = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour
  ) 
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

``` r
colnames(pc_df) = c('product_name', 'Sun', 'Mon', 
                    'Tue', 'Wed', 'Thu', 'Fri', 'Sat')
knitr::kable(pc_df)
```

| product\_name    |      Sun |      Mon |      Tue |      Wed |      Thu |      Fri |      Sat |
|:-----------------|---------:|---------:|---------:|---------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 | 15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 | 14.25000 | 11.55172 | 12.78431 | 11.93750 |

The mean hour of ordering of coffee ice cream is greater than that of
pink lady apples except for Friday.

## Problem 2

Do some data cleaning.

``` r
data("brfss_smart2010")

brfss_df = brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health", response %in% 
           c("Excellent","Very good","Good","Fair","Poor")) %>%
  mutate(response = recode(response,
        "Poor" = "1","Fair" = "2","Good" = "3",
        "Very good" = "4","Excellent" = "5"
        )) %>% 
      arrange(response) %>%  
  mutate(response = recode(response,
        "1" = "Poor","2" = "Fair","3" = "Good",
        "4" = "Very good","5" = "Excellent"
    ))
colnames(brfss_df)[2:3] = c("state","location")
knitr::kable(head(brfss_df[1:4, ]))
```

| year | state | location               | class         | topic          | question                    | response | sample\_size | data\_value | confidence\_limit\_low | confidence\_limit\_high | display\_order | data\_value\_unit | data\_value\_type | data\_value\_footnote\_symbol | data\_value\_footnote | data\_source | class\_id | topic\_id | location\_id | question\_id | respid  | geo\_location           |
|-----:|:------|:-----------------------|:--------------|:---------------|:----------------------------|:---------|-------------:|------------:|-----------------------:|------------------------:|---------------:|:------------------|:------------------|:------------------------------|:----------------------|:-------------|:----------|:----------|:-------------|:-------------|:--------|:------------------------|
| 2010 | AL    | AL - Jefferson County  | Health Status | Overall Health | How is your general health? | Poor     |           45 |         5.5 |                    3.5 |                     7.4 |              5 | %                 | Crude Prevalence  | NA                            | NA                    | BRFSS        | CLASS08   | Topic41   | NA           | GENHLTH      | RESP060 | (33.518601, -86.814688) |
| 2010 | AL    | AL - Mobile County     | Health Status | Overall Health | How is your general health? | Poor     |           66 |         6.4 |                    4.4 |                     8.3 |              5 | %                 | Crude Prevalence  | NA                            | NA                    | BRFSS        | CLASS08   | Topic41   | NA           | GENHLTH      | RESP060 | (30.683993, -88.170637) |
| 2010 | AL    | AL - Tuscaloosa County | Health Status | Overall Health | How is your general health? | Poor     |           35 |         4.2 |                    2.6 |                     5.7 |              5 | %                 | Crude Prevalence  | NA                            | NA                    | BRFSS        | CLASS08   | Topic41   | NA           | GENHLTH      | RESP060 | (33.214154, -87.520229) |
| 2010 | AZ    | AZ - Maricopa County   | Health Status | Overall Health | How is your general health? | Poor     |           62 |         3.5 |                    2.3 |                     4.6 |              5 | %                 | Crude Prevalence  | NA                            | NA                    | BRFSS        | CLASS08   | Topic41   | NA           | GENHLTH      | RESP060 | (33.493403, -112.04143) |

``` r
st_loc02 = brfss_df %>%
  filter(year == "2002") %>%
  group_by(state) %>%
  summarise(location = n()) %>%
  filter(location >= 7) %>%
  arrange(-location)
knitr::kable(head(st_loc02[1:4, ]))
```

| state | location |
|:------|---------:|
| PA    |       50 |
| MA    |       40 |
| NJ    |       40 |
| CT    |       35 |

``` r
st_loc10 = brfss_df %>%
  filter(year == "2010") %>%
  group_by(state) %>%
  summarise(location = n()) %>%
  filter(location >= 7) %>%
  arrange(-location)
knitr::kable(head(st_loc10[1:4, ]))
```

| state | location |
|:------|---------:|
| FL    |      205 |
| NJ    |       95 |
| TX    |       80 |
| CA    |       60 |

In 2002, there were 36 states that were observed at 7 or more locations
and Pennsylvania were observed at 50 locations. In 2010, there were 45
states that were observed at 7 or more locations and Florida were
observed at 205 locations.

``` r
spag_df = brfss_df %>%
  filter(response == "Excellent") %>%
  group_by(state, year) %>%
  summarise(mean_data_value = mean(data_value, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = mean_data_value,
                    color = state), show.legend = FALSE) + 
  geom_line(aes(group = state), alpha = 0.5) + 
  theme(legend.position = "right")
```

    ## `summarise()` has grouped output by 'state'. You can override using the `.groups` argument.

``` r
ggsave("spag_plot.png")
```

    ## Saving 6 x 3.59 in image

``` r
knitr::include_graphics("spag_plot.png")
```

<img src="spag_plot.png" width="90%" />

Different states had different trends. Most of mean\_data\_value were
between 15 and 30.

``` r
panel_df = brfss_df %>%
  filter(state == "NY",
         year %in% c("2006", "2010")) %>% 
  mutate(response = factor(
    response, levels = c("Poor", "Fair", "Good",
                         "Very good", "Excellent"))) %>% 
  ggplot(aes(x = response, y = data_value)) + 
  geom_point(colour = "#FF0000FF") + 
  facet_grid(.~year)

ggsave("two_panel_plot.png")
```

    ## Saving 6 x 3.59 in image

``` r
knitr::include_graphics("two_panel_plot.png")
```

<img src="two_panel_plot.png" width="90%" />

The distributions of data\_value for responses in NY State are similar
for the year 2006 and 2010.

## Problem 3

``` r
accel_df = read_csv("./accel_data.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    week_class = ifelse(
      day %in% c("Sunday", "Saturday"), "Weekend", "Weekday"),
    week = as.integer(week),
    day_id = as.integer(day_id)) %>% 
  relocate(week, day_id, day, week_class)
```

    ## Rows: 35 Columns: 1443

    ## -- Column specification --------------------------------------------------------
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...

    ## 
    ## i Use `spec()` to retrieve the full column specification for this data.
    ## i Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
knitr::kable(head(accel_df[1:4, ]))
```

| week | day\_id | day      | week\_class | activity\_1 | activity\_2 | activity\_3 | activity\_4 | activity\_5 | activity\_6 | activity\_7 | activity\_8 | activity\_9 | activity\_10 | activity\_11 | activity\_12 | activity\_13 | activity\_14 | activity\_15 | activity\_16 | activity\_17 | activity\_18 | activity\_19 | activity\_20 | activity\_21 | activity\_22 | activity\_23 | activity\_24 | activity\_25 | activity\_26 | activity\_27 | activity\_28 | activity\_29 | activity\_30 | activity\_31 | activity\_32 | activity\_33 | activity\_34 | activity\_35 | activity\_36 | activity\_37 | activity\_38 | activity\_39 | activity\_40 | activity\_41 | activity\_42 | activity\_43 | activity\_44 | activity\_45 | activity\_46 | activity\_47 | activity\_48 | activity\_49 | activity\_50 | activity\_51 | activity\_52 | activity\_53 | activity\_54 | activity\_55 | activity\_56 | activity\_57 | activity\_58 | activity\_59 | activity\_60 | activity\_61 | activity\_62 | activity\_63 | activity\_64 | activity\_65 | activity\_66 | activity\_67 | activity\_68 | activity\_69 | activity\_70 | activity\_71 | activity\_72 | activity\_73 | activity\_74 | activity\_75 | activity\_76 | activity\_77 | activity\_78 | activity\_79 | activity\_80 | activity\_81 | activity\_82 | activity\_83 | activity\_84 | activity\_85 | activity\_86 | activity\_87 | activity\_88 | activity\_89 | activity\_90 | activity\_91 | activity\_92 | activity\_93 | activity\_94 | activity\_95 | activity\_96 | activity\_97 | activity\_98 | activity\_99 | activity\_100 | activity\_101 | activity\_102 | activity\_103 | activity\_104 | activity\_105 | activity\_106 | activity\_107 | activity\_108 | activity\_109 | activity\_110 | activity\_111 | activity\_112 | activity\_113 | activity\_114 | activity\_115 | activity\_116 | activity\_117 | activity\_118 | activity\_119 | activity\_120 | activity\_121 | activity\_122 | activity\_123 | activity\_124 | activity\_125 | activity\_126 | activity\_127 | activity\_128 | activity\_129 | activity\_130 | activity\_131 | activity\_132 | activity\_133 | activity\_134 | activity\_135 | activity\_136 | activity\_137 | activity\_138 | activity\_139 | activity\_140 | activity\_141 | activity\_142 | activity\_143 | activity\_144 | activity\_145 | activity\_146 | activity\_147 | activity\_148 | activity\_149 | activity\_150 | activity\_151 | activity\_152 | activity\_153 | activity\_154 | activity\_155 | activity\_156 | activity\_157 | activity\_158 | activity\_159 | activity\_160 | activity\_161 | activity\_162 | activity\_163 | activity\_164 | activity\_165 | activity\_166 | activity\_167 | activity\_168 | activity\_169 | activity\_170 | activity\_171 | activity\_172 | activity\_173 | activity\_174 | activity\_175 | activity\_176 | activity\_177 | activity\_178 | activity\_179 | activity\_180 | activity\_181 | activity\_182 | activity\_183 | activity\_184 | activity\_185 | activity\_186 | activity\_187 | activity\_188 | activity\_189 | activity\_190 | activity\_191 | activity\_192 | activity\_193 | activity\_194 | activity\_195 | activity\_196 | activity\_197 | activity\_198 | activity\_199 | activity\_200 | activity\_201 | activity\_202 | activity\_203 | activity\_204 | activity\_205 | activity\_206 | activity\_207 | activity\_208 | activity\_209 | activity\_210 | activity\_211 | activity\_212 | activity\_213 | activity\_214 | activity\_215 | activity\_216 | activity\_217 | activity\_218 | activity\_219 | activity\_220 | activity\_221 | activity\_222 | activity\_223 | activity\_224 | activity\_225 | activity\_226 | activity\_227 | activity\_228 | activity\_229 | activity\_230 | activity\_231 | activity\_232 | activity\_233 | activity\_234 | activity\_235 | activity\_236 | activity\_237 | activity\_238 | activity\_239 | activity\_240 | activity\_241 | activity\_242 | activity\_243 | activity\_244 | activity\_245 | activity\_246 | activity\_247 | activity\_248 | activity\_249 | activity\_250 | activity\_251 | activity\_252 | activity\_253 | activity\_254 | activity\_255 | activity\_256 | activity\_257 | activity\_258 | activity\_259 | activity\_260 | activity\_261 | activity\_262 | activity\_263 | activity\_264 | activity\_265 | activity\_266 | activity\_267 | activity\_268 | activity\_269 | activity\_270 | activity\_271 | activity\_272 | activity\_273 | activity\_274 | activity\_275 | activity\_276 | activity\_277 | activity\_278 | activity\_279 | activity\_280 | activity\_281 | activity\_282 | activity\_283 | activity\_284 | activity\_285 | activity\_286 | activity\_287 | activity\_288 | activity\_289 | activity\_290 | activity\_291 | activity\_292 | activity\_293 | activity\_294 | activity\_295 | activity\_296 | activity\_297 | activity\_298 | activity\_299 | activity\_300 | activity\_301 | activity\_302 | activity\_303 | activity\_304 | activity\_305 | activity\_306 | activity\_307 | activity\_308 | activity\_309 | activity\_310 | activity\_311 | activity\_312 | activity\_313 | activity\_314 | activity\_315 | activity\_316 | activity\_317 | activity\_318 | activity\_319 | activity\_320 | activity\_321 | activity\_322 | activity\_323 | activity\_324 | activity\_325 | activity\_326 | activity\_327 | activity\_328 | activity\_329 | activity\_330 | activity\_331 | activity\_332 | activity\_333 | activity\_334 | activity\_335 | activity\_336 | activity\_337 | activity\_338 | activity\_339 | activity\_340 | activity\_341 | activity\_342 | activity\_343 | activity\_344 | activity\_345 | activity\_346 | activity\_347 | activity\_348 | activity\_349 | activity\_350 | activity\_351 | activity\_352 | activity\_353 | activity\_354 | activity\_355 | activity\_356 | activity\_357 | activity\_358 | activity\_359 | activity\_360 | activity\_361 | activity\_362 | activity\_363 | activity\_364 | activity\_365 | activity\_366 | activity\_367 | activity\_368 | activity\_369 | activity\_370 | activity\_371 | activity\_372 | activity\_373 | activity\_374 | activity\_375 | activity\_376 | activity\_377 | activity\_378 | activity\_379 | activity\_380 | activity\_381 | activity\_382 | activity\_383 | activity\_384 | activity\_385 | activity\_386 | activity\_387 | activity\_388 | activity\_389 | activity\_390 | activity\_391 | activity\_392 | activity\_393 | activity\_394 | activity\_395 | activity\_396 | activity\_397 | activity\_398 | activity\_399 | activity\_400 | activity\_401 | activity\_402 | activity\_403 | activity\_404 | activity\_405 | activity\_406 | activity\_407 | activity\_408 | activity\_409 | activity\_410 | activity\_411 | activity\_412 | activity\_413 | activity\_414 | activity\_415 | activity\_416 | activity\_417 | activity\_418 | activity\_419 | activity\_420 | activity\_421 | activity\_422 | activity\_423 | activity\_424 | activity\_425 | activity\_426 | activity\_427 | activity\_428 | activity\_429 | activity\_430 | activity\_431 | activity\_432 | activity\_433 | activity\_434 | activity\_435 | activity\_436 | activity\_437 | activity\_438 | activity\_439 | activity\_440 | activity\_441 | activity\_442 | activity\_443 | activity\_444 | activity\_445 | activity\_446 | activity\_447 | activity\_448 | activity\_449 | activity\_450 | activity\_451 | activity\_452 | activity\_453 | activity\_454 | activity\_455 | activity\_456 | activity\_457 | activity\_458 | activity\_459 | activity\_460 | activity\_461 | activity\_462 | activity\_463 | activity\_464 | activity\_465 | activity\_466 | activity\_467 | activity\_468 | activity\_469 | activity\_470 | activity\_471 | activity\_472 | activity\_473 | activity\_474 | activity\_475 | activity\_476 | activity\_477 | activity\_478 | activity\_479 | activity\_480 | activity\_481 | activity\_482 | activity\_483 | activity\_484 | activity\_485 | activity\_486 | activity\_487 | activity\_488 | activity\_489 | activity\_490 | activity\_491 | activity\_492 | activity\_493 | activity\_494 | activity\_495 | activity\_496 | activity\_497 | activity\_498 | activity\_499 | activity\_500 | activity\_501 | activity\_502 | activity\_503 | activity\_504 | activity\_505 | activity\_506 | activity\_507 | activity\_508 | activity\_509 | activity\_510 | activity\_511 | activity\_512 | activity\_513 | activity\_514 | activity\_515 | activity\_516 | activity\_517 | activity\_518 | activity\_519 | activity\_520 | activity\_521 | activity\_522 | activity\_523 | activity\_524 | activity\_525 | activity\_526 | activity\_527 | activity\_528 | activity\_529 | activity\_530 | activity\_531 | activity\_532 | activity\_533 | activity\_534 | activity\_535 | activity\_536 | activity\_537 | activity\_538 | activity\_539 | activity\_540 | activity\_541 | activity\_542 | activity\_543 | activity\_544 | activity\_545 | activity\_546 | activity\_547 | activity\_548 | activity\_549 | activity\_550 | activity\_551 | activity\_552 | activity\_553 | activity\_554 | activity\_555 | activity\_556 | activity\_557 | activity\_558 | activity\_559 | activity\_560 | activity\_561 | activity\_562 | activity\_563 | activity\_564 | activity\_565 | activity\_566 | activity\_567 | activity\_568 | activity\_569 | activity\_570 | activity\_571 | activity\_572 | activity\_573 | activity\_574 | activity\_575 | activity\_576 | activity\_577 | activity\_578 | activity\_579 | activity\_580 | activity\_581 | activity\_582 | activity\_583 | activity\_584 | activity\_585 | activity\_586 | activity\_587 | activity\_588 | activity\_589 | activity\_590 | activity\_591 | activity\_592 | activity\_593 | activity\_594 | activity\_595 | activity\_596 | activity\_597 | activity\_598 | activity\_599 | activity\_600 | activity\_601 | activity\_602 | activity\_603 | activity\_604 | activity\_605 | activity\_606 | activity\_607 | activity\_608 | activity\_609 | activity\_610 | activity\_611 | activity\_612 | activity\_613 | activity\_614 | activity\_615 | activity\_616 | activity\_617 | activity\_618 | activity\_619 | activity\_620 | activity\_621 | activity\_622 | activity\_623 | activity\_624 | activity\_625 | activity\_626 | activity\_627 | activity\_628 | activity\_629 | activity\_630 | activity\_631 | activity\_632 | activity\_633 | activity\_634 | activity\_635 | activity\_636 | activity\_637 | activity\_638 | activity\_639 | activity\_640 | activity\_641 | activity\_642 | activity\_643 | activity\_644 | activity\_645 | activity\_646 | activity\_647 | activity\_648 | activity\_649 | activity\_650 | activity\_651 | activity\_652 | activity\_653 | activity\_654 | activity\_655 | activity\_656 | activity\_657 | activity\_658 | activity\_659 | activity\_660 | activity\_661 | activity\_662 | activity\_663 | activity\_664 | activity\_665 | activity\_666 | activity\_667 | activity\_668 | activity\_669 | activity\_670 | activity\_671 | activity\_672 | activity\_673 | activity\_674 | activity\_675 | activity\_676 | activity\_677 | activity\_678 | activity\_679 | activity\_680 | activity\_681 | activity\_682 | activity\_683 | activity\_684 | activity\_685 | activity\_686 | activity\_687 | activity\_688 | activity\_689 | activity\_690 | activity\_691 | activity\_692 | activity\_693 | activity\_694 | activity\_695 | activity\_696 | activity\_697 | activity\_698 | activity\_699 | activity\_700 | activity\_701 | activity\_702 | activity\_703 | activity\_704 | activity\_705 | activity\_706 | activity\_707 | activity\_708 | activity\_709 | activity\_710 | activity\_711 | activity\_712 | activity\_713 | activity\_714 | activity\_715 | activity\_716 | activity\_717 | activity\_718 | activity\_719 | activity\_720 | activity\_721 | activity\_722 | activity\_723 | activity\_724 | activity\_725 | activity\_726 | activity\_727 | activity\_728 | activity\_729 | activity\_730 | activity\_731 | activity\_732 | activity\_733 | activity\_734 | activity\_735 | activity\_736 | activity\_737 | activity\_738 | activity\_739 | activity\_740 | activity\_741 | activity\_742 | activity\_743 | activity\_744 | activity\_745 | activity\_746 | activity\_747 | activity\_748 | activity\_749 | activity\_750 | activity\_751 | activity\_752 | activity\_753 | activity\_754 | activity\_755 | activity\_756 | activity\_757 | activity\_758 | activity\_759 | activity\_760 | activity\_761 | activity\_762 | activity\_763 | activity\_764 | activity\_765 | activity\_766 | activity\_767 | activity\_768 | activity\_769 | activity\_770 | activity\_771 | activity\_772 | activity\_773 | activity\_774 | activity\_775 | activity\_776 | activity\_777 | activity\_778 | activity\_779 | activity\_780 | activity\_781 | activity\_782 | activity\_783 | activity\_784 | activity\_785 | activity\_786 | activity\_787 | activity\_788 | activity\_789 | activity\_790 | activity\_791 | activity\_792 | activity\_793 | activity\_794 | activity\_795 | activity\_796 | activity\_797 | activity\_798 | activity\_799 | activity\_800 | activity\_801 | activity\_802 | activity\_803 | activity\_804 | activity\_805 | activity\_806 | activity\_807 | activity\_808 | activity\_809 | activity\_810 | activity\_811 | activity\_812 | activity\_813 | activity\_814 | activity\_815 | activity\_816 | activity\_817 | activity\_818 | activity\_819 | activity\_820 | activity\_821 | activity\_822 | activity\_823 | activity\_824 | activity\_825 | activity\_826 | activity\_827 | activity\_828 | activity\_829 | activity\_830 | activity\_831 | activity\_832 | activity\_833 | activity\_834 | activity\_835 | activity\_836 | activity\_837 | activity\_838 | activity\_839 | activity\_840 | activity\_841 | activity\_842 | activity\_843 | activity\_844 | activity\_845 | activity\_846 | activity\_847 | activity\_848 | activity\_849 | activity\_850 | activity\_851 | activity\_852 | activity\_853 | activity\_854 | activity\_855 | activity\_856 | activity\_857 | activity\_858 | activity\_859 | activity\_860 | activity\_861 | activity\_862 | activity\_863 | activity\_864 | activity\_865 | activity\_866 | activity\_867 | activity\_868 | activity\_869 | activity\_870 | activity\_871 | activity\_872 | activity\_873 | activity\_874 | activity\_875 | activity\_876 | activity\_877 | activity\_878 | activity\_879 | activity\_880 | activity\_881 | activity\_882 | activity\_883 | activity\_884 | activity\_885 | activity\_886 | activity\_887 | activity\_888 | activity\_889 | activity\_890 | activity\_891 | activity\_892 | activity\_893 | activity\_894 | activity\_895 | activity\_896 | activity\_897 | activity\_898 | activity\_899 | activity\_900 | activity\_901 | activity\_902 | activity\_903 | activity\_904 | activity\_905 | activity\_906 | activity\_907 | activity\_908 | activity\_909 | activity\_910 | activity\_911 | activity\_912 | activity\_913 | activity\_914 | activity\_915 | activity\_916 | activity\_917 | activity\_918 | activity\_919 | activity\_920 | activity\_921 | activity\_922 | activity\_923 | activity\_924 | activity\_925 | activity\_926 | activity\_927 | activity\_928 | activity\_929 | activity\_930 | activity\_931 | activity\_932 | activity\_933 | activity\_934 | activity\_935 | activity\_936 | activity\_937 | activity\_938 | activity\_939 | activity\_940 | activity\_941 | activity\_942 | activity\_943 | activity\_944 | activity\_945 | activity\_946 | activity\_947 | activity\_948 | activity\_949 | activity\_950 | activity\_951 | activity\_952 | activity\_953 | activity\_954 | activity\_955 | activity\_956 | activity\_957 | activity\_958 | activity\_959 | activity\_960 | activity\_961 | activity\_962 | activity\_963 | activity\_964 | activity\_965 | activity\_966 | activity\_967 | activity\_968 | activity\_969 | activity\_970 | activity\_971 | activity\_972 | activity\_973 | activity\_974 | activity\_975 | activity\_976 | activity\_977 | activity\_978 | activity\_979 | activity\_980 | activity\_981 | activity\_982 | activity\_983 | activity\_984 | activity\_985 | activity\_986 | activity\_987 | activity\_988 | activity\_989 | activity\_990 | activity\_991 | activity\_992 | activity\_993 | activity\_994 | activity\_995 | activity\_996 | activity\_997 | activity\_998 | activity\_999 | activity\_1000 | activity\_1001 | activity\_1002 | activity\_1003 | activity\_1004 | activity\_1005 | activity\_1006 | activity\_1007 | activity\_1008 | activity\_1009 | activity\_1010 | activity\_1011 | activity\_1012 | activity\_1013 | activity\_1014 | activity\_1015 | activity\_1016 | activity\_1017 | activity\_1018 | activity\_1019 | activity\_1020 | activity\_1021 | activity\_1022 | activity\_1023 | activity\_1024 | activity\_1025 | activity\_1026 | activity\_1027 | activity\_1028 | activity\_1029 | activity\_1030 | activity\_1031 | activity\_1032 | activity\_1033 | activity\_1034 | activity\_1035 | activity\_1036 | activity\_1037 | activity\_1038 | activity\_1039 | activity\_1040 | activity\_1041 | activity\_1042 | activity\_1043 | activity\_1044 | activity\_1045 | activity\_1046 | activity\_1047 | activity\_1048 | activity\_1049 | activity\_1050 | activity\_1051 | activity\_1052 | activity\_1053 | activity\_1054 | activity\_1055 | activity\_1056 | activity\_1057 | activity\_1058 | activity\_1059 | activity\_1060 | activity\_1061 | activity\_1062 | activity\_1063 | activity\_1064 | activity\_1065 | activity\_1066 | activity\_1067 | activity\_1068 | activity\_1069 | activity\_1070 | activity\_1071 | activity\_1072 | activity\_1073 | activity\_1074 | activity\_1075 | activity\_1076 | activity\_1077 | activity\_1078 | activity\_1079 | activity\_1080 | activity\_1081 | activity\_1082 | activity\_1083 | activity\_1084 | activity\_1085 | activity\_1086 | activity\_1087 | activity\_1088 | activity\_1089 | activity\_1090 | activity\_1091 | activity\_1092 | activity\_1093 | activity\_1094 | activity\_1095 | activity\_1096 | activity\_1097 | activity\_1098 | activity\_1099 | activity\_1100 | activity\_1101 | activity\_1102 | activity\_1103 | activity\_1104 | activity\_1105 | activity\_1106 | activity\_1107 | activity\_1108 | activity\_1109 | activity\_1110 | activity\_1111 | activity\_1112 | activity\_1113 | activity\_1114 | activity\_1115 | activity\_1116 | activity\_1117 | activity\_1118 | activity\_1119 | activity\_1120 | activity\_1121 | activity\_1122 | activity\_1123 | activity\_1124 | activity\_1125 | activity\_1126 | activity\_1127 | activity\_1128 | activity\_1129 | activity\_1130 | activity\_1131 | activity\_1132 | activity\_1133 | activity\_1134 | activity\_1135 | activity\_1136 | activity\_1137 | activity\_1138 | activity\_1139 | activity\_1140 | activity\_1141 | activity\_1142 | activity\_1143 | activity\_1144 | activity\_1145 | activity\_1146 | activity\_1147 | activity\_1148 | activity\_1149 | activity\_1150 | activity\_1151 | activity\_1152 | activity\_1153 | activity\_1154 | activity\_1155 | activity\_1156 | activity\_1157 | activity\_1158 | activity\_1159 | activity\_1160 | activity\_1161 | activity\_1162 | activity\_1163 | activity\_1164 | activity\_1165 | activity\_1166 | activity\_1167 | activity\_1168 | activity\_1169 | activity\_1170 | activity\_1171 | activity\_1172 | activity\_1173 | activity\_1174 | activity\_1175 | activity\_1176 | activity\_1177 | activity\_1178 | activity\_1179 | activity\_1180 | activity\_1181 | activity\_1182 | activity\_1183 | activity\_1184 | activity\_1185 | activity\_1186 | activity\_1187 | activity\_1188 | activity\_1189 | activity\_1190 | activity\_1191 | activity\_1192 | activity\_1193 | activity\_1194 | activity\_1195 | activity\_1196 | activity\_1197 | activity\_1198 | activity\_1199 | activity\_1200 | activity\_1201 | activity\_1202 | activity\_1203 | activity\_1204 | activity\_1205 | activity\_1206 | activity\_1207 | activity\_1208 | activity\_1209 | activity\_1210 | activity\_1211 | activity\_1212 | activity\_1213 | activity\_1214 | activity\_1215 | activity\_1216 | activity\_1217 | activity\_1218 | activity\_1219 | activity\_1220 | activity\_1221 | activity\_1222 | activity\_1223 | activity\_1224 | activity\_1225 | activity\_1226 | activity\_1227 | activity\_1228 | activity\_1229 | activity\_1230 | activity\_1231 | activity\_1232 | activity\_1233 | activity\_1234 | activity\_1235 | activity\_1236 | activity\_1237 | activity\_1238 | activity\_1239 | activity\_1240 | activity\_1241 | activity\_1242 | activity\_1243 | activity\_1244 | activity\_1245 | activity\_1246 | activity\_1247 | activity\_1248 | activity\_1249 | activity\_1250 | activity\_1251 | activity\_1252 | activity\_1253 | activity\_1254 | activity\_1255 | activity\_1256 | activity\_1257 | activity\_1258 | activity\_1259 | activity\_1260 | activity\_1261 | activity\_1262 | activity\_1263 | activity\_1264 | activity\_1265 | activity\_1266 | activity\_1267 | activity\_1268 | activity\_1269 | activity\_1270 | activity\_1271 | activity\_1272 | activity\_1273 | activity\_1274 | activity\_1275 | activity\_1276 | activity\_1277 | activity\_1278 | activity\_1279 | activity\_1280 | activity\_1281 | activity\_1282 | activity\_1283 | activity\_1284 | activity\_1285 | activity\_1286 | activity\_1287 | activity\_1288 | activity\_1289 | activity\_1290 | activity\_1291 | activity\_1292 | activity\_1293 | activity\_1294 | activity\_1295 | activity\_1296 | activity\_1297 | activity\_1298 | activity\_1299 | activity\_1300 | activity\_1301 | activity\_1302 | activity\_1303 | activity\_1304 | activity\_1305 | activity\_1306 | activity\_1307 | activity\_1308 | activity\_1309 | activity\_1310 | activity\_1311 | activity\_1312 | activity\_1313 | activity\_1314 | activity\_1315 | activity\_1316 | activity\_1317 | activity\_1318 | activity\_1319 | activity\_1320 | activity\_1321 | activity\_1322 | activity\_1323 | activity\_1324 | activity\_1325 | activity\_1326 | activity\_1327 | activity\_1328 | activity\_1329 | activity\_1330 | activity\_1331 | activity\_1332 | activity\_1333 | activity\_1334 | activity\_1335 | activity\_1336 | activity\_1337 | activity\_1338 | activity\_1339 | activity\_1340 | activity\_1341 | activity\_1342 | activity\_1343 | activity\_1344 | activity\_1345 | activity\_1346 | activity\_1347 | activity\_1348 | activity\_1349 | activity\_1350 | activity\_1351 | activity\_1352 | activity\_1353 | activity\_1354 | activity\_1355 | activity\_1356 | activity\_1357 | activity\_1358 | activity\_1359 | activity\_1360 | activity\_1361 | activity\_1362 | activity\_1363 | activity\_1364 | activity\_1365 | activity\_1366 | activity\_1367 | activity\_1368 | activity\_1369 | activity\_1370 | activity\_1371 | activity\_1372 | activity\_1373 | activity\_1374 | activity\_1375 | activity\_1376 | activity\_1377 | activity\_1378 | activity\_1379 | activity\_1380 | activity\_1381 | activity\_1382 | activity\_1383 | activity\_1384 | activity\_1385 | activity\_1386 | activity\_1387 | activity\_1388 | activity\_1389 | activity\_1390 | activity\_1391 | activity\_1392 | activity\_1393 | activity\_1394 | activity\_1395 | activity\_1396 | activity\_1397 | activity\_1398 | activity\_1399 | activity\_1400 | activity\_1401 | activity\_1402 | activity\_1403 | activity\_1404 | activity\_1405 | activity\_1406 | activity\_1407 | activity\_1408 | activity\_1409 | activity\_1410 | activity\_1411 | activity\_1412 | activity\_1413 | activity\_1414 | activity\_1415 | activity\_1416 | activity\_1417 | activity\_1418 | activity\_1419 | activity\_1420 | activity\_1421 | activity\_1422 | activity\_1423 | activity\_1424 | activity\_1425 | activity\_1426 | activity\_1427 | activity\_1428 | activity\_1429 | activity\_1430 | activity\_1431 | activity\_1432 | activity\_1433 | activity\_1434 | activity\_1435 | activity\_1436 | activity\_1437 | activity\_1438 | activity\_1439 | activity\_1440 |
|-----:|--------:|:---------|:------------|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|--------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|---------------:|
|    1 |       1 | Friday   | Weekday     |    88.37778 |    82.24444 |    64.44444 |    70.04444 |    75.04444 |    66.26667 |    53.75556 |    47.84444 |    55.46667 |     42.95556 |     46.75556 |     25.48889 |     18.97778 |     31.11111 |     22.86667 |         24.8 |     51.02222 |     35.48889 |     40.97778 |     59.02222 |     25.17778 |     19.42222 |     44.71111 |     17.13333 |     43.88889 |     47.46667 |     46.11111 |     34.64444 |     40.28889 |     46.46667 |         53.2 |     23.75556 |     35.31111 |     30.66667 |     40.13333 |     25.33333 |     8.888889 |     14.71111 |     18.53333 |     40.68889 |           20 |     37.11111 |         22.6 |     22.77778 |     16.08889 |     29.77778 |     39.44444 |     29.66667 |     54.75556 |     48.26667 |     66.06667 |     65.24444 |     35.68889 |     31.71111 |     26.02222 |     36.62222 |     25.15556 |     27.93333 |     58.02222 |     44.24444 |     46.77778 |     41.73333 |     56.95556 |     51.15556 |     63.53333 |     45.42222 |     44.88889 |     21.71111 |     11.62222 |         37.4 |     36.08889 |         25.8 |     15.11111 |     38.48889 |     46.66667 |     50.11111 |     52.46667 |     67.93333 |     71.35556 |     61.08889 |     35.35556 |     41.48889 |     46.62222 |     38.26667 |     23.35556 |     68.68889 |     44.04444 |     33.82222 |     21.31111 |     37.08889 |         46.8 |     46.86667 |     39.77778 |     26.84444 |     22.66667 |     36.31111 |     33.73333 |     66.95556 |     47.86667 |      38.48889 |      34.73333 |      52.46667 |      24.86667 |          18.8 |      23.75556 |          32.6 |      2.844444 |      11.68889 |      42.53333 |      34.08889 |      31.64444 |          44.4 |      36.66667 |      14.13333 |      20.82222 |      10.95556 |          26.2 |          18.6 |      39.53333 |      11.17778 |      34.02222 |      39.08889 |          46.8 |          44.2 |      40.37778 |      40.88889 |      38.77778 |      19.84444 |      13.51111 |      22.46667 |      18.42222 |      19.73333 |      9.444444 |      20.06667 |      13.97778 |      14.24444 |      12.62222 |      23.71111 |          15.6 |      25.15556 |          23.6 |      16.37778 |      17.22222 |      10.17778 |      8.155556 |      11.62222 |      22.97778 |      20.88889 |      16.46667 |      13.86667 |      7.266667 |             9 |      7.488889 |            14 |      31.15556 |      19.33333 |      15.64444 |      15.64444 |      12.13333 |      14.13333 |      20.55556 |      31.53333 |             4 |      30.62222 |      27.68889 |          14.4 |      44.48889 |      40.35556 |      30.88889 |      25.46667 |            33 |      28.51111 |      61.17778 |      47.48889 |      42.64444 |      21.91111 |      30.31111 |      43.71111 |      65.06667 |      44.91111 |          55.4 |      52.02222 |      75.62222 |      49.22222 |      44.93333 |      42.68889 |      34.55556 |      36.08889 |      53.15556 |      43.17778 |      49.77778 |      45.71111 |      82.93333 |      34.93333 |      52.66667 |      82.28889 |      54.15556 |      42.77778 |      35.48889 |      64.04444 |      42.28889 |      31.88889 |      43.64444 |      57.08889 |      43.26667 |      46.93333 |      52.91111 |          70.8 |      59.22222 |      46.62222 |      36.17778 |      21.35556 |      44.02222 |      50.08889 |      34.22222 |          61.8 |      56.48889 |      46.42222 |      73.73333 |      60.75556 |      49.51111 |      47.13333 |      25.53333 |      54.33333 |      51.77778 |      40.28889 |      72.73333 |      72.17778 |      40.86667 |      50.97778 |      59.06667 |          51.4 |      67.31111 |      80.31111 |          67.2 |      65.86667 |      95.42222 |      37.82222 |      54.28889 |      67.55556 |      47.77778 |      58.22222 |      81.71111 |          62.8 |      49.37778 |          90.2 |      82.84444 |      80.64444 |      61.26667 |      63.66667 |      90.64444 |      105.4667 |      68.62222 |      106.0889 |      84.31111 |          64.8 |      72.48889 |      55.02222 |      47.55556 |      86.84444 |      47.73333 |      45.82222 |      84.86667 |      98.26667 |      113.9111 |      74.13333 |      50.28889 |      71.04444 |      40.04444 |      50.62222 |      49.77778 |      69.06667 |      65.04444 |      95.22222 |      90.22222 |            79 |      100.8444 |      105.9111 |      75.97778 |      67.26667 |      87.48889 |      96.11111 |          66.2 |      91.51111 |          52.4 |      53.93333 |      54.51111 |      72.15556 |      123.3556 |      75.13333 |      83.35556 |      104.1111 |      82.44444 |      118.8444 |      76.48889 |      79.33333 |      99.71111 |      88.73333 |          81.4 |      75.33333 |      117.6667 |      49.26667 |      63.04444 |      99.51111 |      108.9556 |      104.4222 |      115.4222 |      95.13333 |      73.46667 |      107.2889 |      121.1556 |      90.66667 |      113.0444 |      134.9556 |      142.6444 |      142.3778 |      144.6222 |      173.7556 |      137.6667 |         159.2 |           177 |      153.3333 |      145.4889 |      119.5333 |      121.8889 |      108.9556 |      133.8222 |      168.5778 |      194.9778 |      135.6889 |      65.28889 |      58.37778 |      73.91111 |         102.4 |      117.3111 |      107.4222 |      109.0222 |      127.6222 |      149.6667 |      132.5333 |      120.1778 |      102.5333 |      75.97778 |      76.44444 |      85.53333 |      90.33333 |      175.8889 |      175.0444 |      150.6444 |      156.8222 |      124.5778 |      115.0889 |      99.84444 |      119.2889 |      149.5111 |      119.2889 |      126.3778 |      136.8222 |      85.22222 |      107.1556 |      107.5556 |      100.4444 |      140.7333 |      138.0444 |      125.0444 |      129.7333 |         134.2 |      158.4889 |      136.5111 |         127.4 |      157.4444 |      150.8889 |      172.3111 |      158.6889 |      179.5333 |      162.2222 |      183.2889 |      238.5111 |      159.3778 |         207.2 |      212.2889 |      227.2444 |      214.0667 |           210 |      221.0667 |      249.7111 |      202.9333 |      206.0667 |      197.7333 |         218.2 |      214.4889 |      200.4889 |      163.0444 |      160.2444 |      194.0444 |      265.7111 |      230.6889 |      195.5778 |      180.8444 |      171.1333 |      196.3111 |      246.1556 |      272.8889 |      225.4889 |         319.4 |      244.3333 |         206.4 |      225.9333 |      229.4889 |      233.0889 |      215.8444 |      208.1111 |      219.4222 |      272.6444 |      224.2667 |      175.0889 |      162.4444 |      245.6889 |      209.6667 |      176.8889 |         184.6 |      239.4889 |      205.1111 |      189.8667 |         184.8 |      170.3111 |      249.4667 |      244.3778 |      253.4889 |      250.1111 |      258.6667 |      227.9333 |      263.6667 |      231.4667 |      265.2222 |      215.7778 |      245.6222 |      314.6667 |      289.1111 |      290.1111 |      289.0444 |         317.4 |      282.2667 |      276.4444 |      255.7778 |      272.7333 |      282.6444 |      289.5556 |      295.7556 |      345.7556 |      322.4667 |      340.3556 |      296.5778 |         280.6 |      381.9556 |      292.6222 |      284.3556 |      245.6444 |      367.0222 |         299.4 |      257.6667 |      256.1778 |      251.4222 |      275.9778 |      314.1111 |      300.6667 |      190.9778 |      188.9778 |      213.6222 |      277.3778 |      360.3111 |      267.7556 |      316.6222 |      328.2889 |      364.1556 |      301.9778 |      255.8667 |         267.8 |      250.6667 |      242.3333 |      194.1333 |      211.8667 |      261.0889 |      260.1333 |      284.8889 |      294.0444 |         218.6 |      230.0667 |      250.9778 |      224.3111 |         197.6 |      214.5778 |      248.6889 |      221.4444 |      232.4222 |      241.4889 |      223.0444 |      248.2222 |      343.5556 |      277.2222 |         293.4 |      260.8889 |      308.8667 |      341.4667 |      277.9111 |      285.7778 |      338.6818 |      295.7045 |      377.7273 |      252.5909 |      299.2273 |      384.3636 |      318.6591 |      403.0909 |      405.3488 |      333.3488 |       304.093 |      358.7045 |      271.7955 |      253.4651 |      270.7209 |      258.0698 |      193.2093 |      251.8864 |      353.3636 |      301.7273 |      260.6818 |      336.6591 |      282.0682 |      317.8182 |      374.7111 |      324.3333 |      321.4889 |      344.4783 |      288.8913 |      320.2174 |       299.413 |      298.6304 |           262 |      357.3043 |      394.3913 |             1 |           335 |           738 |           580 |           779 |           717 |          3423 |          3008 |          6997 |          5236 |           675 |           580 |           845 |           492 |            11 |            11 |           150 |           226 |          1035 |          1596 |           200 |            22 |           379 |           542 |           127 |            95 |            53 |            43 |           127 |           291 |           137 |           425 |            11 |           458 |           291 |           188 |           106 |            95 |            53 |             1 |           717 |            85 |           188 |           960 |          1701 |           188 |           137 |           127 |           238 |           291 |           238 |           276 |           137 |           150 |            53 |           150 |           200 |           137 |            74 |           200 |            95 |           618 |           542 |           305 |           137 |             1 |          1195 |           891 |           779 |           305 |           137 |           127 |            95 |            11 |           656 |          1401 |          1140 |          1140 |           393 |           696 |           891 |           738 |           291 |           891 |           580 |           364 |           349 |             1 |            32 |            11 |             1 |           475 |           845 |            22 |           150 |           458 |          1035 |          1035 |           696 |            11 |            22 |            43 |            85 |             1 |             1 |           200 |           127 |           320 |           335 |           364 |            11 |            43 |            22 |            22 |            85 |           475 |          1401 |          1140 |           320 |           263 |            64 |            53 |            64 |           238 |           675 |          1222 |           599 |           509 |           475 |            22 |             1 |            11 |           137 |           492 |             1 |           163 |            74 |           175 |            53 |            43 |            11 |           150 |            95 |           349 |           599 |           263 |           618 |           561 |           425 |           779 |          1113 |          1340 |           738 |          1432 |           200 |          1010 |           759 |           238 |             1 |           188 |            22 |            53 |             1 |             1 |           599 |           821 |           937 |          1113 |           291 |          1222 |           393 |           675 |           580 |           561 |           542 |           238 |           305 |            95 |            32 |           213 |           937 |           116 |            85 |           458 |           200 |           175 |            74 |            53 |           200 |           226 |            32 |            53 |             1 |            64 |           263 |           291 |          1113 |           891 |           868 |           696 |          1195 |           891 |          1252 |           821 |          1113 |           637 |          1401 |          1168 |          1195 |           379 |          1113 |          1562 |           779 |           542 |           364 |            43 |           150 |           759 |           580 |           349 |           175 |           580 |           696 |           845 |           408 |           276 |           580 |           868 |           276 |           276 |           696 |            85 |            43 |            11 |            64 |             1 |            11 |             1 |            11 |            32 |           251 |            11 |             1 |           175 |            11 |            22 |             1 |             1 |             1 |           175 |           200 |            32 |             1 |           163 |           106 |           238 |           509 |           561 |           263 |            85 |            53 |             1 |             1 |             1 |           393 |           779 |             1 |             1 |           150 |            22 |            43 |            43 |             1 |            11 |             1 |             1 |           200 |             1 |            11 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |           914 |           263 |            43 |           226 |            95 |            43 |             1 |             1 |           251 |           349 |            43 |           251 |            32 |             1 |            11 |           492 |             1 |            11 |           150 |           188 |            43 |           137 |           200 |           116 |           188 |             1 |            53 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |            11 |             1 |             1 |             1 |             1 |            53 |             1 |             1 |             1 |             1 |             1 |             1 |           458 |           891 |            85 |            64 |            85 |             1 |             1 |            11 |             1 |           599 |          1140 |           408 |            43 |           379 |           263 |           150 |            64 |             1 |            43 |           305 |           213 |            43 |            53 |             1 |             1 |             1 |             1 |             1 |           150 |            64 |           238 |           364 |           188 |           238 |           188 |           116 |             1 |             1 |             1 |           335 |           891 |          1010 |           492 |            43 |            53 |           458 |            74 |           251 |           238 |            53 |           393 |           335 |           305 |           675 |           891 |           175 |           442 |           364 |           891 |           738 |           349 |           291 |           821 |           458 |            64 |            32 |            32 |           106 |            53 |            85 |           163 |           175 |             1 |             1 |           175 |           408 |           656 |            64 |           379 |           845 |           425 |          1401 |           580 |           717 |           637 |           188 |           349 |           599 |             1 |            95 |            74 |            53 |             1 |           137 |           163 |           276 |           845 |            64 |             1 |            22 |           821 |            64 |            163 |            127 |            251 |             32 |            175 |             11 |             85 |              1 |              1 |              1 |              1 |            276 |              1 |              1 |              1 |            226 |              1 |            188 |              1 |             32 |             95 |              1 |             32 |             43 |              1 |              1 |             85 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |             43 |              1 |            599 |            821 |            188 |              1 |            226 |            263 |            320 |            868 |            656 |            163 |            276 |            137 |             64 |             22 |             43 |             53 |            393 |              1 |             53 |             11 |             22 |             11 |             11 |              1 |            116 |           1195 |            475 |            305 |            509 |            320 |            263 |             32 |              1 |             11 |              1 |             64 |            106 |             64 |             53 |            637 |            442 |            408 |              1 |              1 |             32 |              1 |             11 |              1 |             32 |              1 |            408 |            127 |             11 |            188 |             32 |              1 |             64 |            335 |            580 |           1310 |           1222 |            738 |           2259 |            868 |            618 |            656 |           1281 |           1432 |           1113 |            800 |            425 |            937 |            263 |            656 |            696 |            200 |            492 |            779 |            200 |             74 |            163 |             32 |            150 |             11 |             43 |              1 |             32 |       226.0000 |       137.0000 |          263.0 |       580.0000 |       800.0000 |       845.0000 |      1529.0000 |       542.0000 |      1140.0000 |       251.0000 |        64.0000 |        85.0000 |       263.0000 |       305.0000 |        95.0000 |      1562.0000 |       845.0000 |       475.0000 |      1432.0000 |       509.0000 |       251.0000 |       175.0000 |          492.0 |       188.0000 |       868.0000 |       779.0000 |          116.0 |           11.0 |        53.0000 |       305.0000 |       442.0000 |       960.0000 |       779.0000 |       127.0000 |       200.0000 |          251.0 |       276.0000 |        22.0000 |       821.0000 |       868.0000 |       637.0000 |       116.0000 |        95.0000 |       226.0000 |       408.0000 |       656.0000 |       175.0000 |        32.0000 |       393.0000 |       379.0000 |       238.0000 |       137.0000 |       213.0000 |       561.0000 |       425.0000 |       320.0000 |       263.0000 |       335.0000 |          238.0 |       717.0000 |       127.0000 |       263.0000 |        32.0000 |       251.0000 |       526.0000 |       914.0000 |       200.0000 |         1369.0 |       542.0000 |          717.0 |      1222.0000 |      1629.0000 |       542.0000 |       580.0000 |       868.0000 |      1113.0000 |       891.0000 |        43.0000 |       561.0000 |       891.0000 |       891.0000 |       251.0000 |       891.0000 |      2215.0000 |      3300.0000 |      2349.0000 |      2087.0000 |       618.0000 |      3008.0000 |      2005.0000 |         1086.0 |          175.0 |      1736.0000 |       213.0000 |       656.0000 |      1222.0000 |       717.0000 |       251.0000 |       393.0000 |       561.0000 |      1061.0000 |      1401.0000 |      1772.0000 |      2349.0000 |       759.0000 |      2586.0000 |         1810.0 |      1340.0000 |      1113.0000 |      2844.0000 |       960.0000 |       163.0000 |      1885.0000 |      1629.0000 |      1885.0000 |       845.0000 |      1701.0000 |      2045.0000 |      1010.0000 |       985.0000 |       779.0000 |      1401.0000 |      1596.0000 |      1281.0000 |      1810.0000 |         1035.0 |      2259.0000 |        43.0000 |      1736.0000 |       717.0000 |      5906.0000 |      5419.0000 |      1281.0000 |      1736.0000 |      1562.0000 |      1168.0000 |       458.0000 |      2303.0000 |      1596.0000 |      1168.0000 |       580.0000 |       188.0000 |          675.0 |       599.0000 |       526.0000 |          251.0 |      1281.0000 |      2538.0000 |      4970.0000 |          985.0 |       276.0000 |      2490.0000 |         1140.0 |      3952.0000 |      2792.0000 |      1340.0000 |      1281.0000 |      2687.0000 |      1810.0000 |      3549.0000 |      3121.0000 |      2792.0000 |      1885.0000 |      1810.0000 |      1195.0000 |       175.0000 |        64.0000 |        74.0000 |        85.0000 |       637.0000 |       305.0000 |       759.0000 |         1035.0 |       738.0000 |       442.0000 |       226.0000 |       800.0000 |       542.0000 |       738.0000 |       618.0000 |         1086.0 |          458.0 |       458.0000 |       349.0000 |          116.0 |        11.0000 |       238.0000 |       175.0000 |       116.0000 |       656.0000 |       127.0000 |       116.0000 |       276.0000 |       150.0000 |       276.0000 |       738.0000 |       305.0000 |       599.0000 |       509.0000 |            1.0 |       116.0000 |       349.0000 |        11.0000 |            364 |       163.0000 |       251.0000 |       263.0000 |       127.0000 |        64.0000 |       127.0000 |        64.0000 |       364.0000 |          226.0 |       137.0000 |       116.0000 |        74.0000 |        85.0000 |        43.0000 |         1.0000 |       263.0000 |      1222.0000 |       335.0000 |       618.0000 |        22.0000 |        32.0000 |          914.0 |          226.0 |        53.0000 |        64.0000 |       599.0000 |        22.0000 |       175.0000 |        53.0000 |       542.0000 |       200.0000 |       335.0000 |      150.00000 |       475.0000 |       116.0000 |       320.0000 |        85.0000 |       305.0000 |      526.00000 |       263.0000 |       618.0000 |      2005.0000 |       150.0000 |      821.00000 |      393.00000 |     1772.00000 |      599.00000 |      1596.0000 |      1035.0000 |       492.0000 |       458.0000 |         1061.0 |       492.0000 |          320.0 |       759.0000 |      1086.0000 |       276.0000 |       618.0000 |       542.0000 |      1168.0000 |       779.0000 |          509.0 |       599.0000 |      1432.0000 |       509.0000 |       891.0000 |       914.0000 |       526.0000 |       717.0000 |       561.0000 |       349.0000 |      937.00000 |            891 |      150.00000 |       85.00000 |      127.00000 |      213.00000 |       74.00000 |      349.00000 |        1.00000 |      251.00000 |      637.00000 |      238.00000 |      226.00000 |      599.00000 |      526.00000 |      393.00000 |      127.00000 |       22.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |            1.0 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |
|    1 |       2 | Monday   | Weekday     |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |     1.000000 |      1.00000 |      1.00000 |      1.00000 |            1 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      1.000000 |             1 |      1.000000 |             1 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |        1.0000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |             1 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |             1 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |         1.000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |         1.000 |        1.0000 |             1 |        1.0000 |        1.0000 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |              1 |       411.7111 |       383.3556 |          442.6 |       341.7556 |       344.1778 |       333.6667 |       317.3778 |       401.6222 |       352.1111 |       238.8667 |       224.6444 |       332.9333 |       327.3556 |       299.3556 |       360.8222 |       293.3111 |       314.0889 |       323.9556 |       378.8222 |       300.2444 |       294.3778 |       270.0222 |          335.8 |       365.8222 |       395.7556 |       444.7333 |          352.8 |          381.6 |       314.2444 |       255.1111 |       377.9556 |       295.2889 |       279.3556 |       307.6444 |       362.5556 |          335.6 |       400.2667 |       412.6889 |       339.1556 |       362.8889 |       301.1333 |       366.3778 |       373.2667 |       425.2889 |       452.1333 |       374.1333 |       496.0222 |       460.7111 |       393.1111 |       327.5333 |       464.8667 |       265.1111 |       269.8444 |       363.7111 |       271.2444 |       367.5778 |       345.1556 |       274.2222 |          262.2 |       252.1556 |       240.8444 |       278.6222 |       276.2222 |       253.3333 |       233.0444 |       235.4667 |       261.0222 |          197.2 |       249.1111 |          183.6 |       176.7778 |       255.3111 |       239.3778 |       260.9556 |       274.0667 |       229.1556 |       315.4222 |       313.4222 |       322.3778 |       361.9111 |       344.0222 |       345.6667 |       382.5556 |       407.1778 |       345.1556 |       300.7111 |       346.2222 |       436.8889 |       313.2667 |       246.6444 |          326.4 |          435.2 |       341.6222 |       404.6667 |       415.4889 |       396.6889 |       298.5778 |       338.5111 |       392.6667 |       342.9556 |       438.4889 |       349.6222 |       300.7556 |       285.7333 |       226.4889 |       303.0667 |          366.4 |       326.5556 |       389.3556 |       287.8889 |       317.4222 |       237.6667 |       260.0889 |       296.6222 |       248.2889 |       324.8889 |       335.7778 |       399.2667 |       393.2889 |       481.8444 |       394.3556 |       465.9111 |       362.1333 |       353.3111 |       404.5556 |          406.6 |       310.4444 |       437.8889 |       360.6667 |       411.5556 |       332.1778 |       233.7778 |       332.6889 |       388.2889 |       290.6667 |       318.9333 |       335.3111 |       342.0889 |       424.4667 |       394.8889 |       429.3778 |       421.9556 |          529.6 |       515.1556 |       516.5556 |          486.2 |       352.6444 |       402.2667 |       326.1111 |          360.6 |       344.5333 |       372.7556 |          400.4 |       304.9556 |       331.6889 |       344.4444 |       298.3778 |       348.8667 |       257.6444 |       292.2222 |       342.7333 |       308.0889 |       311.6889 |       312.5111 |       250.3778 |       176.2889 |       181.3556 |       215.3778 |       335.9333 |       137.8889 |       202.9556 |       237.8222 |          226.2 |       269.5556 |       348.4222 |       211.5111 |       255.7778 |       197.7556 |       199.7111 |       199.8889 |          180.8 |          219.6 |       178.9111 |       162.0667 |          210.8 |       197.2444 |       149.8444 |       215.7111 |       269.1778 |       269.0222 |       328.8889 |       210.7333 |       254.7778 |       230.7556 |       265.8444 |       222.3333 |       230.7333 |       214.0667 |       174.6667 |          232.6 |       224.2222 |       215.9333 |       164.7778 |            186 |       205.1556 |       178.4889 |       150.0889 |       184.0889 |       162.2444 |       166.4889 |       196.7111 |       168.0667 |          154.4 |       150.7778 |       196.7778 |       190.4222 |       212.4667 |       208.1556 |       214.3778 |       220.0667 |       148.9556 |       138.5333 |       156.3556 |       136.2889 |       176.8889 |          212.4 |          140.6 |       152.3111 |       133.5333 |       216.5111 |       139.1111 |       152.4222 |       191.5556 |       193.8444 |       133.4889 |       112.3333 |       89.84444 |       205.7111 |       169.5111 |       128.5778 |       127.2444 |       135.3111 |       90.62222 |       142.3556 |       169.3333 |       180.8444 |       122.5778 |       96.31111 |       86.48889 |       93.88889 |       93.35556 |       114.2889 |       132.3556 |       145.1111 |       107.8222 |          123.6 |       158.6889 |          164.4 |       106.2444 |       157.6667 |       158.1778 |       157.8667 |       151.9778 |       121.4889 |       155.2444 |          174.2 |       127.0444 |       163.1333 |       162.8222 |       187.6222 |       142.3556 |       114.4222 |       148.1111 |       101.0667 |       100.3111 |       83.66667 |            104 |       69.46667 |       67.13333 |       68.68889 |       96.75556 |       60.02222 |       66.82222 |       62.37778 |       79.35556 |       48.06667 |       92.44444 |       89.66667 |       90.44444 |       58.06667 |       60.77778 |       67.08889 |       35.51111 |       47.44444 |       36.77778 |       58.71111 |       68.86667 |           66.8 |       78.28889 |       79.17778 |       50.84444 |       73.62222 |       54.51111 |       60.75556 |       54.46667 |       24.55556 |       21.88889 |       16.64444 |       35.53333 |       31.71111 |       67.68889 |
|    1 |       3 | Saturday | Weekend     |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |        379.0 |    696.00000 |    759.00000 |   1168.00000 |    150.00000 |     53.00000 |    95.000000 |    150.00000 |     32.00000 |     74.00000 |          137 |    305.00000 |        305.0 |     43.00000 |     85.00000 |     64.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |     11.00000 |      1.00000 |     11.00000 |      1.00000 |          1.0 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      74.00000 |      74.00000 |     580.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |      1.000000 |       1.00000 |       1.00000 |     526.00000 |     509.00000 |      43.00000 |      1.000000 |             1 |      1.000000 |             1 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |          32.0 |       1.00000 |       1.00000 |      95.00000 |       1.00000 |       1.00000 |      32.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      22.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      74.00000 |       1.00000 |     759.00000 |          32.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |           1.0 |       1.00000 |     188.00000 |       1.00000 |       1.00000 |       1.00000 |      22.00000 |       1.00000 |      64.00000 |          32.0 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |      53.00000 |        1.0000 |       1.00000 |        1.0000 |       1.00000 |           1.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |          85.0 |     188.00000 |         175.0 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |       1.00000 |        1.0000 |       1.00000 |        1.0000 |     127.00000 |       1.00000 |      64.00000 |       1.00000 |           1.0 |       1.00000 |      251.0000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |      11.00000 |       1.00000 |      137.0000 |        1.0000 |       1.00000 |       11.0000 |        1.0000 |       53.0000 |        1.0000 |      305.0000 |        1.0000 |       11.0000 |         393.0 |             1 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       85.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |     150.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |      238.0000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       32.0000 |           1.0 |        1.0000 |      127.0000 |        1.0000 |             1 |        1.0000 |        1.0000 |       74.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |      379.0000 |        1.0000 |      251.0000 |       43.0000 |        1.0000 |        1.0000 |       74.0000 |      150.0000 |      137.0000 |      305.0000 |         335.0 |       32.0000 |          11.0 |      320.0000 |       85.0000 |      150.0000 |        1.0000 |      335.0000 |      175.0000 |        1.0000 |        1.0000 |      276.0000 |        1.0000 |      106.0000 |      175.0000 |      291.0000 |         509.0 |      821.0000 |      213.0000 |      475.0000 |         458.0 |     1140.0000 |      226.0000 |      349.0000 |      561.0000 |      305.0000 |      251.0000 |      200.0000 |      675.0000 |      200.0000 |      475.0000 |      542.0000 |      364.0000 |      800.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |       85.0000 |      175.0000 |      106.0000 |       74.0000 |      364.0000 |       85.0000 |      188.0000 |      238.0000 |      779.0000 |      137.0000 |           1.0 |        1.0000 |      364.0000 |       11.0000 |      251.0000 |        1.0000 |           1.0 |      891.0000 |      561.0000 |       32.0000 |       85.0000 |      226.0000 |       95.0000 |      213.0000 |      580.0000 |      213.0000 |       53.0000 |      150.0000 |      320.0000 |      127.0000 |        1.0000 |       43.0000 |        1.0000 |        1.0000 |          64.0 |       74.0000 |       11.0000 |      379.0000 |      335.0000 |      127.0000 |      960.0000 |        1.0000 |      137.0000 |         263.0 |        1.0000 |        1.0000 |        1.0000 |           1.0 |      379.0000 |        1.0000 |       22.0000 |      106.0000 |      127.0000 |       64.0000 |        1.0000 |      163.0000 |      335.0000 |         320.0 |      364.0000 |      188.0000 |       95.0000 |       64.0000 |      738.0000 |      868.0000 |      696.0000 |      150.0000 |      251.0000 |      163.0000 |       53.0000 |       32.0000 |        1.0000 |        1.0000 |        1.0000 |         1.000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |      561.0000 |      213.0000 |       22.0000 |        1.0000 |      379.0000 |      960.0000 |     1701.0000 |      779.0000 |      868.0000 |      821.0000 |      599.0000 |      800.0000 |      717.0000 |      759.0000 |      759.0000 |       475.000 |      821.0000 |          1529 |     1464.0000 |     1965.0000 |           137 |           618 |           526 |            74 |           599 |          1140 |           779 |           937 |           696 |          1168 |          1401 |          1562 |           914 |           599 |           845 |           238 |            11 |           116 |             1 |           106 |            74 |           759 |          1035 |           561 |           349 |           759 |          1061 |           696 |           393 |           425 |           379 |           213 |           637 |           637 |           320 |           393 |           263 |           276 |           868 |           800 |           106 |           226 |           509 |            22 |           175 |           127 |            11 |             1 |           127 |           291 |           320 |           914 |            53 |           106 |            64 |           116 |           442 |           458 |           526 |           175 |            95 |           305 |           637 |           238 |           116 |           200 |           349 |           542 |           349 |           263 |           238 |           542 |            22 |             1 |            11 |            74 |           188 |           458 |           150 |           200 |           251 |           509 |            53 |          1629 |            32 |           263 |           408 |           188 |           127 |           696 |          1701 |           150 |           320 |           127 |            64 |           226 |           320 |           821 |           364 |          1010 |           821 |           127 |             1 |           213 |             1 |           379 |          1252 |           868 |          1222 |           291 |            95 |           349 |           393 |           163 |           175 |           127 |           175 |           542 |           320 |           656 |           349 |           738 |          1369 |          1432 |           150 |            22 |             1 |             1 |            43 |           106 |           251 |           188 |            95 |           393 |           276 |           580 |           492 |           637 |            95 |           276 |           127 |            43 |           960 |           696 |            95 |            85 |          1061 |           738 |           599 |           937 |           393 |           599 |           526 |          1432 |           759 |           492 |           599 |           116 |           475 |           845 |           408 |           580 |           379 |            32 |           150 |           349 |           335 |           276 |           320 |           116 |           116 |             1 |            64 |            11 |             1 |            74 |           475 |           738 |           845 |           580 |          1340 |           845 |          1195 |            85 |          1252 |          1252 |           675 |           914 |           891 |           800 |           364 |            95 |            64 |            85 |           696 |           263 |           291 |           393 |            32 |            85 |           200 |           637 |           717 |           305 |           188 |           226 |           408 |           759 |           580 |           509 |           618 |            95 |           561 |           238 |           425 |           238 |           393 |           868 |          1252 |           492 |           509 |           226 |           188 |           542 |           305 |            85 |           150 |           251 |           492 |           106 |            95 |           656 |           213 |           106 |            85 |            32 |           137 |           200 |           379 |           599 |          1168 |           226 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |             1 |           200 |           738 |           200 |           188 |           335 |           238 |           364 |           960 |          1432 |          1495 |           821 |           800 |           561 |           738 |          1222 |          1113 |          1464 |           526 |           291 |            32 |           137 |            95 |           150 |           800 |           845 |           960 |           335 |           163 |           150 |           393 |           458 |           425 |           845 |           364 |           364 |           127 |           320 |           526 |           561 |           305 |           349 |           738 |           393 |           561 |           335 |           759 |           738 |           821 |           759 |           599 |           291 |           349 |           475 |           561 |           656 |          1010 |           425 |           492 |          1222 |           263 |            11 |            22 |            32 |           800 |          1310 |           759 |          1562 |          2215 |          1061 |          2303 |           821 |           800 |           291 |           291 |           188 |           291 |           263 |           349 |           226 |           238 |           442 |          1195 |          1810 |          1195 |          1168 |          2259 |           618 |            32 |            22 |           263 |           821 |           188 |           251 |           163 |           458 |           717 |           717 |           226 |             1 |           127 |           408 |           291 |          1061 |           675 |           845 |           891 |          1222 |          1252 |           891 |           349 |          1432 |           442 |           937 |           335 |           276 |          1369 |            95 |           116 |             1 |           163 |           637 |           305 |           188 |           251 |           276 |           200 |           127 |             1 |           526 |           349 |           305 |           580 |           238 |           137 |           213 |           320 |           238 |            22 |           106 |           263 |           868 |           276 |           137 |           656 |           379 |           960 |           738 |          1401 |          1113 |          1464 |           106 |           509 |           150 |           291 |            53 |           200 |           106 |           188 |           509 |            32 |           637 |           868 |           408 |           213 |           175 |           656 |          1140 |          1495 |            11 |            11 |           335 |           127 |           349 |           717 |           127 |           526 |           200 |           127 |           379 |           379 |           188 |           163 |           442 |           618 |           379 |           276 |           188 |            11 |            11 |            22 |            53 |            22 |            53 |           175 |           213 |           213 |           320 |           213 |            85 |            32 |           238 |           442 |           127 |           175 |            74 |           127 |            53 |             85 |            213 |            213 |            425 |            226 |            335 |           1035 |            717 |            675 |            738 |           1464 |            542 |            213 |            276 |            137 |            305 |             32 |            251 |            163 |            238 |            526 |            106 |            276 |            738 |            393 |            408 |            238 |            425 |            937 |           1401 |           1848 |            717 |            891 |            759 |            542 |            475 |            509 |            425 |            276 |            779 |            458 |            116 |             64 |            637 |            637 |            868 |            738 |           1222 |            656 |            475 |           1113 |            821 |           1281 |            213 |            335 |             22 |            349 |            580 |             64 |            542 |            127 |            349 |            163 |            985 |            845 |           1113 |            717 |            800 |            509 |            213 |            408 |             32 |            561 |            106 |            163 |             64 |            305 |             11 |              1 |            137 |            251 |              1 |              1 |              1 |              1 |              1 |             64 |             11 |              1 |             85 |            425 |            116 |            717 |            213 |              1 |            442 |            509 |            238 |            226 |              1 |            561 |             64 |             64 |            137 |            116 |            188 |             43 |            163 |            127 |              1 |             11 |            188 |              1 |              1 |             22 |             11 |              1 |             95 |            127 |             32 |            106 |            150 |            116 |             11 |              1 |              1 |              1 |             11 |             74 |            106 |        53.0000 |        22.0000 |           32.0 |        64.0000 |         1.0000 |        43.0000 |       106.0000 |         1.0000 |         1.0000 |       393.0000 |        22.0000 |         1.0000 |        11.0000 |       106.0000 |        85.0000 |        11.0000 |        85.0000 |       226.0000 |         1.0000 |        43.0000 |       116.0000 |         1.0000 |           11.0 |         1.0000 |       213.0000 |       137.0000 |           95.0 |            1.0 |       213.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |       251.0000 |       425.0000 |          349.0 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        11.0000 |         1.0000 |        95.0000 |       175.0000 |         1.0000 |        43.0000 |        32.0000 |         1.0000 |        64.0000 |        22.0000 |        11.0000 |       251.0000 |         1.0000 |         1.0000 |        32.0000 |           11.0 |       163.0000 |        11.0000 |         1.0000 |        22.0000 |        85.0000 |        53.0000 |        85.0000 |        85.0000 |          188.0 |       276.0000 |          458.0 |        11.0000 |       106.0000 |        11.0000 |        53.0000 |        22.0000 |        64.0000 |        22.0000 |         1.0000 |       137.0000 |       200.0000 |       213.0000 |        11.0000 |       150.0000 |       150.0000 |         1.0000 |         1.0000 |        95.0000 |        32.0000 |         1.0000 |         1.0000 |          106.0 |          106.0 |         1.0000 |        64.0000 |         1.0000 |       150.0000 |        74.0000 |         1.0000 |        53.0000 |        95.0000 |       238.0000 |       914.0000 |       821.0000 |       800.0000 |       937.0000 |       779.0000 |          509.0 |      1340.0000 |       937.0000 |      1035.0000 |      1464.0000 |      1140.0000 |      1252.0000 |      1035.0000 |      1340.0000 |       618.0000 |       561.0000 |       696.0000 |      1086.0000 |       305.0000 |       656.0000 |       492.0000 |       845.0000 |       845.0000 |        11.0000 |          163.0 |       492.0000 |       738.0000 |       320.0000 |       542.0000 |       175.0000 |        95.0000 |        53.0000 |       213.0000 |       163.0000 |       137.0000 |        53.0000 |       116.0000 |        85.0000 |       200.0000 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |           53.0 |        22.0000 |       458.0000 |          599.0 |      1086.0000 |       349.0000 |       696.0000 |       937.0000 |       738.0000 |       675.0000 |       599.0000 |      1010.0000 |       821.0000 |       675.0000 |       509.0000 |      2637.0000 |      1885.0000 |      1281.0000 |      1401.0000 |      1168.0000 |       526.0000 |       251.0000 |       561.0000 |         1086.0 |       675.0000 |       492.0000 |       656.0000 |       561.0000 |       458.0000 |       188.0000 |       821.0000 |          335.0 |          364.0 |      1310.0000 |      1035.0000 |          759.0 |       526.0000 |       937.0000 |       509.0000 |      1010.0000 |       738.0000 |       542.0000 |       868.0000 |        53.0000 |      1035.0000 |       656.0000 |       696.0000 |        32.0000 |       868.0000 |       492.0000 |          150.0 |      1629.0000 |        74.0000 |       320.0000 |            127 |       263.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        11.0000 |        11.0000 |          127.0 |        32.0000 |         1.0000 |        85.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |           32.0 |            1.0 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        1.00000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        1.00000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |           85.0 |        74.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |        32.0000 |         1.0000 |        11.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        1.00000 |              1 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |            1.0 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |        1.00000 |       53.00000 |        1.00000 |      213.00000 |        1.00000 |       22.00000 |        1.00000 |
|    1 |       4 | Sunday   | Weekend     |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |     1.00000 |      1.00000 |      1.00000 |      1.00000 |     32.00000 |      1.00000 |      1.00000 |          1.0 |     32.00000 |      1.00000 |     85.00000 |    116.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |     11.00000 |      1.00000 |    150.00000 |      1.00000 |         11.0 |      1.00000 |      1.00000 |     64.00000 |    276.00000 |      1.00000 |     1.000000 |      1.00000 |      1.00000 |      1.00000 |            1 |      1.00000 |          1.0 |      1.00000 |    163.00000 |      1.00000 |      1.00000 |      1.00000 |     95.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |     11.00000 |     43.00000 |      1.00000 |      1.00000 |      1.00000 |     74.00000 |      1.00000 |     74.00000 |     85.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |          1.0 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |      1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |         106.0 |       1.00000 |           1.0 |     32.000000 |       1.00000 |       1.00000 |      43.00000 |       1.00000 |          43.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |          22.0 |          32.0 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |           1.0 |       1.00000 |     213.00000 |      85.00000 |       1.00000 |       1.00000 |      74.00000 |      11.00000 |       1.00000 |      1.000000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |     226.00000 |           1.0 |       1.00000 |           1.0 |       1.00000 |      32.00000 |     137.00000 |    175.000000 |      11.00000 |     226.00000 |      95.00000 |     305.00000 |     526.00000 |    509.000000 |           868 |      1.000000 |            22 |     137.00000 |       1.00000 |       1.00000 |       1.00000 |      22.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |      53.00000 |       1.00000 |         335.0 |     960.00000 |     717.00000 |     188.00000 |      64.00000 |            11 |      64.00000 |       1.00000 |       1.00000 |     821.00000 |     150.00000 |     188.00000 |     106.00000 |     116.00000 |     291.00000 |         408.0 |     251.00000 |     349.00000 |     364.00000 |     150.00000 |      22.00000 |      22.00000 |     213.00000 |     675.00000 |     291.00000 |     960.00000 |     442.00000 |     116.00000 |     150.00000 |      11.00000 |     238.00000 |     238.00000 |      22.00000 |      43.00000 |       1.00000 |       1.00000 |      43.00000 |      11.00000 |     305.00000 |     599.00000 |     442.00000 |     779.00000 |         821.0 |      64.00000 |       1.00000 |       1.00000 |      11.00000 |       1.00000 |     276.00000 |      22.00000 |          64.0 |     599.00000 |     759.00000 |     821.00000 |     637.00000 |      74.00000 |      53.00000 |      43.00000 |      32.00000 |       1.00000 |     175.00000 |     960.00000 |     442.00000 |     821.00000 |     821.00000 |     442.00000 |         656.0 |     696.00000 |     675.00000 |         561.0 |     561.00000 |     425.00000 |     779.00000 |    1010.00000 |     175.00000 |     393.00000 |     364.00000 |     599.00000 |         580.0 |     393.00000 |         226.0 |     226.00000 |     263.00000 |     868.00000 |     492.00000 |     821.00000 |      675.0000 |     349.00000 |      320.0000 |     442.00000 |         320.0 |     127.00000 |     509.00000 |       1.00000 |       1.00000 |      85.00000 |       1.00000 |       1.00000 |       1.00000 |       32.0000 |       1.00000 |      64.00000 |     379.00000 |     200.00000 |      74.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |             1 |      175.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |     509.00000 |         150.0 |     526.00000 |     393.00000 |      11.00000 |       11.0000 |      22.00000 |     127.00000 |        1.0000 |      74.00000 |        1.0000 |     163.00000 |     175.00000 |       1.00000 |      53.00000 |          95.0 |      74.00000 |      175.0000 |     226.00000 |     251.00000 |     106.00000 |       64.0000 |        1.0000 |       32.0000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |             1 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |       1.00000 |       1.00000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |      150.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       1.00000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |             1 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |      200.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       32.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |        1.0000 |        1.0000 |          43.0 |        1.0000 |      251.0000 |      291.0000 |       43.0000 |       11.0000 |       43.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |       95.0000 |        1.0000 |        1.0000 |        1.0000 |        1.0000 |           1.0 |        1.0000 |       64.0000 |        1.0000 |      137.0000 |       32.0000 |        1.0000 |        1.0000 |        1.0000 |       22.0000 |      263.0000 |       43.0000 |         106.0 |       64.0000 |       53.0000 |       11.0000 |      127.0000 |       53.0000 |           1.0 |      106.0000 |      599.0000 |      263.0000 |     1401.0000 |      618.0000 |      580.0000 |      675.0000 |      779.0000 |      106.0000 |      458.0000 |      717.0000 |      821.0000 |     1010.0000 |      458.0000 |      580.0000 |      759.0000 |     1772.0000 |         891.0 |     1222.0000 |     1168.0000 |      637.0000 |     1810.0000 |     1596.0000 |      561.0000 |      738.0000 |      759.0000 |         542.0 |      526.0000 |     1596.0000 |      599.0000 |        1010.0 |      349.0000 |      580.0000 |      656.0000 |      492.0000 |      914.0000 |      637.0000 |      364.0000 |      542.0000 |      492.0000 |         379.0 |      599.0000 |      580.0000 |      349.0000 |      137.0000 |      226.0000 |      213.0000 |       43.0000 |      526.0000 |      542.0000 |      238.0000 |      364.0000 |      305.0000 |      150.0000 |      442.0000 |      137.0000 |         1.000 |        1.0000 |        1.0000 |      188.0000 |     1010.0000 |     1010.0000 |      561.0000 |      675.0000 |      717.0000 |      717.0000 |     1252.0000 |     1061.0000 |      599.0000 |      675.0000 |      408.0000 |      821.0000 |     1113.0000 |      458.0000 |      393.0000 |      937.0000 |       458.000 |     1495.0000 |           637 |     1310.0000 |      320.0000 |          1010 |           458 |           492 |          1529 |          2259 |           914 |          1010 |          1086 |           960 |           937 |           580 |           618 |           985 |          1310 |          1529 |           779 |           985 |           738 |           656 |          2441 |          1596 |          1035 |          1925 |          2171 |           800 |          1736 |          1772 |          1061 |           238 |           458 |           821 |           738 |           717 |          1252 |           985 |           238 |           580 |          1736 |          1529 |          1310 |           656 |           821 |          1222 |           868 |           637 |           492 |           738 |          1340 |           738 |          1281 |          1010 |          1113 |           985 |           759 |          1010 |           442 |           717 |           291 |           599 |           599 |           738 |           891 |           845 |           379 |           580 |           675 |           238 |           226 |           442 |           675 |           800 |           320 |           188 |           393 |           599 |           580 |            85 |           960 |           675 |           637 |           458 |          1252 |           759 |           542 |           127 |             1 |           364 |           637 |           637 |           425 |            22 |           175 |           492 |           379 |            22 |             1 |           127 |            74 |           238 |           475 |             1 |           542 |           320 |           492 |           276 |           188 |           425 |          1464 |          2441 |          1925 |          1772 |          2441 |          1665 |           116 |          1401 |          2171 |          3614 |          4397 |          1401 |          3300 |          2303 |          6214 |          1222 |           599 |           845 |          1035 |           960 |           263 |            64 |           175 |           914 |          1195 |          5058 |          1885 |          3549 |           891 |           106 |           492 |           226 |            95 |           106 |           213 |             1 |           320 |           599 |          1369 |          1596 |           868 |          2490 |          7866 |          4554 |          4244 |           263 |           492 |            22 |           738 |           305 |           937 |          1562 |          3121 |          1965 |           717 |           599 |          1772 |            74 |            43 |          1464 |           891 |           393 |           696 |          1252 |            11 |             1 |          1113 |           188 |           150 |          1885 |           188 |           150 |            95 |            22 |            11 |           914 |           200 |          2844 |          1925 |            43 |           696 |           960 |          1195 |           759 |            11 |            53 |             1 |           213 |           106 |           175 |            64 |            32 |            11 |           408 |          1086 |            85 |          1369 |          1596 |          2538 |          1195 |          1495 |           475 |           656 |           914 |            11 |           458 |           960 |            74 |           425 |           475 |           263 |           291 |          1885 |          1168 |          1701 |          1369 |          1885 |          2792 |          2215 |          2171 |          1701 |           442 |           960 |          1340 |           475 |           291 |           696 |            11 |           637 |           475 |           509 |            32 |             1 |             1 |            43 |           175 |           891 |          1168 |          1810 |           937 |           475 |          1464 |           200 |           675 |          2005 |          1195 |           759 |           821 |            11 |             1 |             1 |            11 |             1 |             1 |             1 |             1 |             1 |           106 |           163 |           305 |           379 |            53 |             1 |             1 |           238 |           561 |           200 |           379 |           163 |           163 |           163 |             1 |           226 |           675 |           150 |           475 |          1281 |           779 |          2792 |           914 |           738 |           251 |           335 |           291 |           238 |            43 |           188 |           492 |           526 |          1281 |           696 |           305 |           349 |           116 |          1086 |          1113 |           779 |           891 |          1252 |          1168 |           637 |           442 |           106 |           868 |           335 |           188 |           868 |           320 |           364 |           349 |           291 |            32 |            64 |           349 |           150 |           580 |           845 |             1 |           238 |           137 |           408 |           800 |           914 |           492 |           738 |           759 |           408 |           393 |           779 |           408 |           238 |           561 |           656 |           349 |          1252 |           379 |           163 |           696 |          1464 |          1140 |           393 |          1061 |           542 |           425 |           779 |           759 |           542 |           526 |           188 |           127 |           150 |            43 |           150 |            22 |           263 |            53 |           106 |           238 |            85 |           116 |           188 |           200 |            32 |           442 |           561 |           127 |            64 |             1 |             1 |            32 |            11 |           349 |            43 |            32 |           238 |           492 |          1495 |           891 |           800 |          1369 |           291 |           379 |           393 |           845 |           200 |           226 |           845 |           637 |           800 |           276 |           408 |           251 |           116 |           291 |           320 |           291 |          1222 |           509 |           492 |          1629 |           779 |           637 |           779 |           738 |           561 |           175 |           408 |           291 |           599 |          4716 |          2844 |          1281 |           779 |           845 |           526 |           821 |            95 |           238 |           937 |          2171 |          1665 |          2005 |          1113 |          1401 |          1113 |          1010 |          1086 |           379 |           188 |           150 |           580 |           675 |           759 |           985 |           656 |           349 |           305 |           580 |           408 |           868 |          1562 |          1113 |          1401 |          3952 |          3883 |          1736 |           868 |           238 |            22 |           800 |           379 |              1 |            492 |            200 |            127 |            106 |            276 |              1 |            349 |            188 |             22 |            305 |           2303 |           2395 |            150 |            985 |            492 |           1401 |            637 |           1140 |            696 |            738 |           1529 |           2844 |           1562 |            561 |           2441 |            656 |           1113 |           1562 |           3883 |            106 |             85 |            526 |            335 |            200 |             85 |              1 |              1 |             11 |            251 |            379 |           1113 |           1113 |            937 |            458 |           1810 |            985 |           1810 |           1885 |            458 |           1401 |            656 |           1281 |           2538 |           1665 |           2303 |            821 |            675 |            717 |            845 |           1086 |            150 |             74 |             95 |            127 |            251 |              1 |             53 |              1 |              1 |              1 |             43 |            291 |             95 |            425 |             74 |            200 |            291 |            580 |           1113 |            637 |            226 |              1 |            188 |              1 |            127 |            127 |            845 |            526 |             22 |            458 |            914 |            960 |            408 |            675 |            475 |            561 |           1529 |            150 |            238 |            393 |             22 |              1 |            458 |            213 |            408 |            116 |             95 |            408 |            509 |            106 |            320 |            137 |            291 |             53 |             32 |            509 |            150 |            188 |            213 |             11 |            213 |             95 |             74 |             11 |             11 |            675 |            526 |            408 |            175 |       305.0000 |       800.0000 |         1310.0 |       656.0000 |      2045.0000 |       914.0000 |       226.0000 |      1252.0000 |      1010.0000 |       349.0000 |       127.0000 |       116.0000 |       717.0000 |       618.0000 |      1168.0000 |       738.0000 |      1010.0000 |      1885.0000 |      1401.0000 |      1061.0000 |      1222.0000 |       779.0000 |         1222.0 |       335.0000 |       821.0000 |       320.0000 |           64.0 |           64.0 |      1596.0000 |       458.0000 |        95.0000 |       393.0000 |         1.0000 |         1.0000 |         1.0000 |          891.0 |       116.0000 |       150.0000 |       150.0000 |       213.0000 |       291.0000 |       127.0000 |       188.0000 |       150.0000 |        53.0000 |         1.0000 |        53.0000 |       291.0000 |       509.0000 |       213.0000 |       580.0000 |         1.0000 |       393.0000 |       442.0000 |       276.0000 |       379.0000 |       291.0000 |       960.0000 |          442.0 |       509.0000 |       137.0000 |       175.0000 |       425.0000 |        53.0000 |       175.0000 |       263.0000 |        22.0000 |          276.0 |        22.0000 |           11.0 |       188.0000 |        85.0000 |         1.0000 |        22.0000 |        53.0000 |        11.0000 |       213.0000 |        74.0000 |        32.0000 |       175.0000 |        22.0000 |       188.0000 |         1.0000 |         1.0000 |        85.0000 |        32.0000 |       163.0000 |        32.0000 |        85.0000 |        11.0000 |            1.0 |            1.0 |       213.0000 |       150.0000 |       492.0000 |         1.0000 |        64.0000 |         1.0000 |       163.0000 |       263.0000 |       188.0000 |       137.0000 |       738.0000 |        53.0000 |       226.0000 |       150.0000 |          561.0 |         1.0000 |       106.0000 |        43.0000 |        22.0000 |       276.0000 |       320.0000 |       238.0000 |        32.0000 |         1.0000 |        22.0000 |        53.0000 |        11.0000 |         1.0000 |         1.0000 |       188.0000 |         1.0000 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        11.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |        11.0000 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |            1.0 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |         1.0000 |       379.0000 |       364.0000 |       618.0000 |       738.0000 |       175.0000 |          542.0 |      1310.0000 |       759.0000 |       226.0000 |       425.0000 |      1086.0000 |       213.0000 |        11.0000 |          116.0 |          526.0 |       868.0000 |       561.0000 |          291.0 |        22.0000 |       637.0000 |      1195.0000 |       868.0000 |       561.0000 |       263.0000 |       475.0000 |       675.0000 |       821.0000 |      1010.0000 |        22.0000 |        74.0000 |       213.0000 |       150.0000 |          542.0 |       150.0000 |       137.0000 |         1.0000 |             43 |       291.0000 |        85.0000 |         1.0000 |        11.0000 |       226.0000 |       175.0000 |       116.0000 |       599.0000 |           53.0 |       188.0000 |       442.0000 |       127.0000 |        43.0000 |        64.0000 |       127.0000 |        95.0000 |         1.0000 |       175.0000 |       442.0000 |       580.0000 |       106.0000 |           53.0 |          150.0 |       116.0000 |       137.0000 |        95.0000 |       163.0000 |       106.0000 |       213.0000 |        11.0000 |        74.0000 |         1.0000 |       95.00000 |       200.0000 |       137.0000 |        74.0000 |       542.0000 |       251.0000 |      116.00000 |       759.0000 |       379.0000 |       845.0000 |      1195.0000 |      868.00000 |     1086.00000 |     1086.00000 |      618.00000 |       263.0000 |       349.0000 |       779.0000 |      1432.0000 |          656.0 |       150.0000 |          175.0 |       200.0000 |       175.0000 |       717.0000 |       891.0000 |      1281.0000 |      1035.0000 |       238.0000 |          759.0 |       759.0000 |      1529.0000 |      1596.0000 |      1529.0000 |       960.0000 |        74.0000 |        22.0000 |        53.0000 |       393.0000 |       64.00000 |              1 |       32.00000 |       11.00000 |      137.00000 |       11.00000 |       43.00000 |       74.00000 |       64.00000 |       43.00000 |       22.00000 |      127.00000 |       22.00000 |      226.00000 |      116.00000 |        1.00000 |      137.00000 |       32.00000 |      492.00000 |     1061.00000 |      779.00000 |     1629.00000 |          150.0 |     1310.00000 |      526.00000 |      188.00000 |       53.00000 |       11.00000 |      675.00000 |      175.00000 |      106.00000 |       95.00000 |      675.00000 |      393.00000 |       22.00000 |      305.00000 |

This dataset has 35 observations and 1444 variables. Variables include
“week”, “day\_id”, “day”, “week\_class” and 1440 “activity\_i” variables
which are the activity counts for each minute of a 24-hour day starting
at midnight.

``` r
agg_min_df = accel_df %>%
  mutate(activity_day = rowSums(accel_df[,c(5:1444)])) %>%
  relocate(week, day_id, day, week_class, activity_day)

tot_df = agg_min_df %>%
  group_by(day) %>%
  summarise(tot_act = sum(activity_day))
knitr::kable(tot_df)
```

| day       | tot\_act |
|:----------|---------:|
| Friday    |  2291711 |
| Monday    |  1858699 |
| Saturday  |  1369237 |
| Sunday    |  1919213 |
| Thursday  |  2091151 |
| Tuesday   |  1799238 |
| Wednesday |  2129772 |

The patient usually has higher activity counts at the middle of a week,
i.e. Wednesday, Thursday and Friday.

``` r
accel_panel_df = accel_df %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = "activity_min",
    values_to = "activity_counts",
    names_prefix = "activity_"
  ) %>%
  mutate(activity_min = as.numeric(activity_min)) %>%
  group_by(day, activity_min ) %>%
  summarise(sum_activity_counts = sum(activity_counts)) %>%
  filter(sum_activity_counts > 2000) %>%
  mutate(day = factor(
    day, levels = c("Sunday", "Monday", "Tuesday",
                         "Wednesday", "Thursday", "Friday", "Saturday"))) %>%
  ggplot(aes(x = activity_min, y = sum_activity_counts, 
           group = day, color = day)) + 
  geom_point(alpha = 0.5) 
```

    ## `summarise()` has grouped output by 'day'. You can override using the `.groups` argument.

``` r
ggsave("accel_panel_plot.png")
```

    ## Saving 6 x 3.59 in image

``` r
knitr::include_graphics("accel_panel_plot.png")
```

<img src="accel_panel_plot.png" width="90%" />

The activity counts rose significantly on Friday around 9 PM and
Saturday around 11 AM.
